### ISSUE TITLE
Which structure drawing software do you use?

### ISSUE THREAD

**Issue by weixsun** [ChenKangQiang/spring-boot-demo#7]
I take the liberty to interrupt you. Didn’t find your email, so I can only take an improper way. I saw your structure diagram in [#26126](https://github.com/spring-projects/spring-boot/issues/26126) in spring boot issues. I think it is very concise. I would like to know which software you used to draw it?

![image](https://user-images.githubusercontent.com/29357333/116788827-62ae8c00-aade-11eb-9b5d-ac6a088774bb.png)

Sorry again for my abruptness

**Comment by ChenKangQiang** [comment]
@weixsun draw.io

**Comment by ChenKangQiang** [comment]
https://drawio-app.com/

**Comment by weixsun** [comment]
Great, thanks, i'll try it
